name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t wishercarts/docker-hello-test:actions .

      - name: Push Docker image
        run: docker push wishercarts/docker-hello-test:actions